require 'simplecov'
SimpleCov.start
require './lib/writer'
require './lib/reader'
require './lib/translate_to_english'
require './lib/translate_to_braille'
require './lib/dictionary'
require './lib/letter'
require 'rspec'
require 'csv'
